"A datetime string with format `Y-m-d H:i:s`, e.g. `2018-05-23 13:43:32`."
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

"Indicates what fields are available at the top level of a query operation."
type Query {
    "Find a single user by an identifying attribute."
    user(
      "Search by primary key."
      id: ID @eq @rules(apply: ["prohibits:email", "required_without:email"])

      "Search by email address."
      email: String @eq @rules(apply: ["prohibits:id", "required_without:id", "email"])
    ): User @find

    "List multiple users."
    users(
      "Filters by name. Accepts SQL LIKE wildcards `%` and `_`."
      name: String @where(operator: "like")
    ): [User!]! @paginate(defaultCount: 10)

    "Find all tasks."
    tasks: [Task!]! @all

    "Find a single task by an identifying attribute."
    task(id: ID! @eq): Task @find
}

"Account of a person who uses this application."
type User {
    "Unique primary key."
    id: ID!

    "Non-unique name."
    name: String!

    "Unique email address."
    email: String!

    "When the email was verified."
    email_verified_at: DateTime

    "When the account was created."
    created_at: DateTime!

    "When the account was last updated."
    updated_at: DateTime!
}

type Task {
    id: ID!
    title: String!
    description: String
    is_completed: Boolean!
    created_at: String!
    updated_at: String!
}

"Indicates what fields are available at the top level of a mutation operation."
type Mutation {
    createTask(title: String!, description: String): Task @create
    updateTask(id: ID!, title: String, description: String, is_completed: Boolean): Task @update
    deleteTask(id: ID!): Task @delete
}
